name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit and Integration tests
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: changeThePassword

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            if mongo --host localhost --eval 'db.runCommand({ ping: 1 })'; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB to be ready..."
            sleep 2
          done
          echo "MongoDB did not become ready in time!"
          exit 1

      - name: Run tests
        run: make test
